import os
import re
import json
import frontmatter

class SearchWorker:
    """A bot that searches for a specific keyword within an authorized subset of the vault."""
    
    def __init__(self, vault_path="knowledge"):
        self.vault_path = vault_path

    def search(self, keyword, allowed_subsets=None):
        """High-speed search using the JSON cache generated by VaultWarden."""
        if not allowed_subsets:
            return []

        results = []
        keyword = keyword.lower()
        
        cache_path = os.path.join(self.vault_path, "_SEARCH_CACHE.json")
        if not os.path.exists(cache_path):
            print("⚠️ Cache not found. Running slow search...")
            return self._slow_search(keyword, allowed_subsets)

        with open(cache_path, 'r', encoding='utf-8') as f:
            cache_data = json.load(f)

        # Determine actual subsets to search
        target_subsets = []
        if allowed_subsets == "ALL":
            target_subsets = cache_data.keys()
        else:
            target_subsets = allowed_subsets

        for subset in target_subsets:
            if subset not in cache_data: continue
            
            for doc in cache_data[subset]:
                relevance = 0
                title = doc["title"].lower()
                tags = str(doc.get("tags", [])).lower()
                summary = doc.get("summary", "").lower()
                
                if keyword in title: relevance += 10
                if keyword in tags: relevance += 5
                if keyword in summary: relevance += 3
                
                if relevance > 0:
                    # Construct full path for Orchestrator to read
                    full_path = os.path.join(self.vault_path, subset, doc["path"])
                    results.append({
                        "path": full_path,
                        "title": doc["title"],
                        "relevance": relevance,
                        "department": subset,
                        "tags": doc["tags"],
                        "summary": doc["summary"],
                        "doc_id": doc.get("doc_id", "N/A"),
                    })
        
        return results

    def _slow_search(self, keyword, allowed_subsets):
        """Fallback: walk markdown vault when _SEARCH_CACHE.json is missing."""
        results = []
        keyword = keyword.lower()
        if not allowed_subsets:
            return results

        if allowed_subsets == "ALL":
            if not os.path.isdir(self.vault_path):
                return results
            target_subsets = [
                d for d in os.listdir(self.vault_path)
                if os.path.isdir(os.path.join(self.vault_path, d)) and not d.startswith("_")
            ]
        else:
            target_subsets = list(allowed_subsets)

        for subset in target_subsets:
            dept_dir = os.path.join(self.vault_path, subset)
            if not os.path.isdir(dept_dir):
                continue
            for file in os.listdir(dept_dir):
                if not file.endswith(".md") or file.startswith("_"):
                    continue
                file_path = os.path.join(dept_dir, file)
                try:
                    post = frontmatter.load(file_path)
                except Exception:
                    continue
                title = (post.get("title") or file).lower()
                tags = str(post.get("tags", [])).lower()
                summary = (post.get("summary") or "").lower()
                relevance = 0
                if keyword in title:
                    relevance += 10
                if keyword in tags:
                    relevance += 5
                if keyword in summary:
                    relevance += 3
                if relevance > 0:
                    results.append({
                        "path": file_path,
                        "title": post.get("title", file),
                        "relevance": relevance,
                        "department": subset,
                        "tags": post.get("tags", []),
                        "summary": post.get("summary", ""),
                        "doc_id": post.get("doc_id", "N/A"),
                    })
        return results
